
backend:
  name: git-gateway
  branch: main
  repo: yosephdev/portfolio-website # Your GitHub username/repo

# When using a custom domain for the CMS
site_url: https://yoseph.dev
display_url: https://yoseph.dev

media_folder: "public/images/uploads" # Media will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Reading Time", name: "readingTime", widget: "string", default: "5 min read"}
      - {label: "Author", name: "author", widget: "string", default: "Yoseph Berhane"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "Related Posts", name: "relatedPosts", widget: "list", required: false}

  - name: "projects" # Used in routes, e.g., /admin/collections/projects
    label: "Projects" # Used in the UI
    folder: "src/content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Long Description", name: "longDescription", widget: "markdown"}
      - {label: "Technologies", name: "tech", widget: "list"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Screenshots", name: "screenshots", widget: "list", field: {label: "Image", name: "image", widget: "image"}, required: false}
      - {label: "GitHub URL", name: "github", widget: "string", required: false}
      - {label: "Live Demo URL", name: "url", widget: "string", required: false}
